version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/types"
    versions:
    - 7.12.12
    - 7.12.13
    - 7.12.17
    - 7.13.0
    - 7.13.12
    - 7.13.13
    - 7.13.14
    - 7.13.17
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@babel/traverse"
    versions:
    - 7.12.13
    - 7.12.17
    - 7.13.0
    - 7.13.13
    - 7.13.15
  - dependency-name: "@types/babel__core"
    versions:
    - 7.1.13
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.16.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.4
